# Condor scrpit for ntuple process
# This should only be used when the EP and AP shares the same file system
executable		= CutOpt.sh

transfer_input_files	= CutOpt.C
#output                  = $(Process).o
error                   = error/CutOpt/$(Process).err
should_transfer_files	= IF_NEEDED
when_to_transfer_output	= ON_EXIT

request_cpus		= 48
request_memory		= 512M
request_disk		= 256M

max_retries		= 2
# variable names here
queue arguments from (
    LIST
)