executable          	= /home/storage29/users/junkaiqin/X3872Analysis/cutopt.sh
transfer_input_files	= CutOptimization.C, X3872Utils.h
should_transfer_files	= YES
when_to_transfer_output	= ON_EXIT_OR_EVICT
output              	= /home/storage29/users/junkaiqin/X3872Analysis/output/cutopt/$(Process).out
error               	= /home/storage29/users/junkaiqin/X3872Analysis/error/cutopt/$(Process).err
log                 	= /home/storage29/users/junkaiqin/X3872Analysis/cutopt.log
request_cpus        	= 48
request_memory      	= 4096 MB
request_disk        	= 256 MB
rank                	= TotalCpus
queue arguments from (
    LIST
)